### PR TITLE
fix: REPL style insert in FireFox

### LINKED ISSUE #1161: spiral example does not work in firefox
| chrome | firefox |
| :-: | :-: |
| image | image |

[link](https://preactjs.com/repl/?example=spiral)

using firefox developer edition, 128.0b9 (64-bit, arm64, mac)

### PR DESCRIPTION
**Pull request by rschristian**
Fixes #1161 

The information on this is a bit lacking, but it seems FireFox asynchronously creates the iframe doc once appended into the parent whereas Chrome and Safari do it synchronously, then, upon loading, FireFox will replace the inserted document if it's already been altered? Not 100% on that, but this seems to do the trick.

### CODE REVIEW

File: src/components/controllers/repl/runner.jsx [hunk 1]
```diff
@@ -112,16 +112,25 @@ export default class Runner extends Component {
...
-				${this.props.css || ''}
-			`)
-		);
-		doc.head.appendChild(style);
-		createRoot(doc);
+
+		const insertStyles = () => {
+			const doc = this.realm.globalThis.document,
+				style = doc.createElement('style');
+
```
Comment (rschristian) [inline src/components/controllers/repl/runner.jsx:119]:
```suggestion
```

File: src/components/controllers/repl/runner.jsx [hunk 2]
```diff
@@ -112,16 +112,25 @@ export default class Runner extends Component {
...
+			style.appendChild(
+				doc.createTextNode(`
+					html { font: 100%/1.3 system-ui, sans-serif; background: none; }
+					${this.props.css || ''}
+				`)
+			);
+			doc.head.appendChild(style);
+
```
Comment (rschristian) [inline src/components/controllers/repl/runner.jsx:127]:
```suggestion
```

**Review by JoviDeCroock — APPROVED** [review]
